name: Publish

on:
    create:
        branches: [ main ]
    push:
        branches: [ main ]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    publish:
        runs-on: macos-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
                distribution: 'zulu'
                java-version: 11
          - name: Cache Build files
            uses: actions/cache@v3
            with:
                path: |
                    ~/.konan
                    ~/.gradle
                key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v1
          - uses: gradle/gradle-build-action@v2
            name: Publish
            with:
                arguments: clean publish